/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCliPushRouteImport } from './routes/api/cli/push'
import { Route as ApiCliPullRouteImport } from './routes/api/cli/pull'
import { Route as ApiCliInitRouteImport } from './routes/api/cli/init'
import { Route as ApiCliDiffRouteImport } from './routes/api/cli/diff'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliPushRoute = ApiCliPushRouteImport.update({
  id: '/api/cli/push',
  path: '/api/cli/push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliPullRoute = ApiCliPullRouteImport.update({
  id: '/api/cli/pull',
  path: '/api/cli/pull',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliInitRoute = ApiCliInitRouteImport.update({
  id: '/api/cli/init',
  path: '/api/cli/init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliDiffRoute = ApiCliDiffRouteImport.update({
  id: '/api/cli/diff',
  path: '/api/cli/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cli/diff': typeof ApiCliDiffRoute
  '/api/cli/init': typeof ApiCliInitRoute
  '/api/cli/pull': typeof ApiCliPullRoute
  '/api/cli/push': typeof ApiCliPushRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cli/diff': typeof ApiCliDiffRoute
  '/api/cli/init': typeof ApiCliInitRoute
  '/api/cli/pull': typeof ApiCliPullRoute
  '/api/cli/push': typeof ApiCliPushRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cli/diff': typeof ApiCliDiffRoute
  '/api/cli/init': typeof ApiCliInitRoute
  '/api/cli/pull': typeof ApiCliPullRoute
  '/api/cli/push': typeof ApiCliPushRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api/auth/$'
    | '/api/cli/diff'
    | '/api/cli/init'
    | '/api/cli/pull'
    | '/api/cli/push'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api/auth/$'
    | '/api/cli/diff'
    | '/api/cli/init'
    | '/api/cli/pull'
    | '/api/cli/push'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api/auth/$'
    | '/api/cli/diff'
    | '/api/cli/init'
    | '/api/cli/pull'
    | '/api/cli/push'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCliDiffRoute: typeof ApiCliDiffRoute
  ApiCliInitRoute: typeof ApiCliInitRoute
  ApiCliPullRoute: typeof ApiCliPullRoute
  ApiCliPushRoute: typeof ApiCliPushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/push': {
      id: '/api/cli/push'
      path: '/api/cli/push'
      fullPath: '/api/cli/push'
      preLoaderRoute: typeof ApiCliPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/pull': {
      id: '/api/cli/pull'
      path: '/api/cli/pull'
      fullPath: '/api/cli/pull'
      preLoaderRoute: typeof ApiCliPullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/init': {
      id: '/api/cli/init'
      path: '/api/cli/init'
      fullPath: '/api/cli/init'
      preLoaderRoute: typeof ApiCliInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/diff': {
      id: '/api/cli/diff'
      path: '/api/cli/diff'
      fullPath: '/api/cli/diff'
      preLoaderRoute: typeof ApiCliDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCliDiffRoute: ApiCliDiffRoute,
  ApiCliInitRoute: ApiCliInitRoute,
  ApiCliPullRoute: ApiCliPullRoute,
  ApiCliPushRoute: ApiCliPushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
