/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteInvitationIdRouteImport } from './routes/invite.$invitationId'
import { Route as ApiHealthzRouteImport } from './routes/api/healthz'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedBillingRouteImport } from './routes/_authed/billing'
import { Route as AuthedBillingIndexRouteImport } from './routes/_authed/billing.index'
import { Route as ApiCliPushRouteImport } from './routes/api/cli/push'
import { Route as ApiCliPullRouteImport } from './routes/api/cli/pull'
import { Route as ApiCliInitRouteImport } from './routes/api/cli/init'
import { Route as ApiCliDiffRouteImport } from './routes/api/cli/diff'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedProjectsProjectIdRouteImport } from './routes/_authed/projects/$projectId'
import { Route as AuthedBillingCheckoutRouteImport } from './routes/_authed/billing.checkout'
import { Route as AuthedProjectsProjectIdIndexRouteImport } from './routes/_authed/projects/$projectId/index'
import { Route as ApiEnvironmentsEnvironmentIdDownloadRouteImport } from './routes/api/environments/$environmentId/download'
import { Route as AuthedProjectsProjectIdSettingsRouteImport } from './routes/_authed/projects/$projectId/settings'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteInvitationIdRoute = InviteInvitationIdRouteImport.update({
  id: '/invite/$invitationId',
  path: '/invite/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthzRoute = ApiHealthzRouteImport.update({
  id: '/api/healthz',
  path: '/api/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBillingRoute = AuthedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBillingIndexRoute = AuthedBillingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedBillingRoute,
} as any)
const ApiCliPushRoute = ApiCliPushRouteImport.update({
  id: '/api/cli/push',
  path: '/api/cli/push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliPullRoute = ApiCliPullRouteImport.update({
  id: '/api/cli/pull',
  path: '/api/cli/pull',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliInitRoute = ApiCliInitRouteImport.update({
  id: '/api/cli/init',
  path: '/api/cli/init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliDiffRoute = ApiCliDiffRouteImport.update({
  id: '/api/cli/diff',
  path: '/api/cli/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProjectsProjectIdRoute = AuthedProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBillingCheckoutRoute = AuthedBillingCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthedBillingRoute,
} as any)
const AuthedProjectsProjectIdIndexRoute =
  AuthedProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)
const ApiEnvironmentsEnvironmentIdDownloadRoute =
  ApiEnvironmentsEnvironmentIdDownloadRouteImport.update({
    id: '/api/environments/$environmentId/download',
    path: '/api/environments/$environmentId/download',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthedProjectsProjectIdSettingsRoute =
  AuthedProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/billing': typeof AuthedBillingRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/billing/checkout': typeof AuthedBillingCheckoutRoute
  '/projects/$projectId': typeof AuthedProjectsProjectIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cli/diff': typeof ApiCliDiffRoute
  '/api/cli/init': typeof ApiCliInitRoute
  '/api/cli/pull': typeof ApiCliPullRoute
  '/api/cli/push': typeof ApiCliPushRoute
  '/billing/': typeof AuthedBillingIndexRoute
  '/projects/$projectId/settings': typeof AuthedProjectsProjectIdSettingsRoute
  '/api/environments/$environmentId/download': typeof ApiEnvironmentsEnvironmentIdDownloadRoute
  '/projects/$projectId/': typeof AuthedProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/billing/checkout': typeof AuthedBillingCheckoutRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cli/diff': typeof ApiCliDiffRoute
  '/api/cli/init': typeof ApiCliInitRoute
  '/api/cli/pull': typeof ApiCliPullRoute
  '/api/cli/push': typeof ApiCliPushRoute
  '/billing': typeof AuthedBillingIndexRoute
  '/projects/$projectId/settings': typeof AuthedProjectsProjectIdSettingsRoute
  '/api/environments/$environmentId/download': typeof ApiEnvironmentsEnvironmentIdDownloadRoute
  '/projects/$projectId': typeof AuthedProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/about': typeof AboutRoute
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authed/billing': typeof AuthedBillingRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/_authed/billing/checkout': typeof AuthedBillingCheckoutRoute
  '/_authed/projects/$projectId': typeof AuthedProjectsProjectIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cli/diff': typeof ApiCliDiffRoute
  '/api/cli/init': typeof ApiCliInitRoute
  '/api/cli/pull': typeof ApiCliPullRoute
  '/api/cli/push': typeof ApiCliPushRoute
  '/_authed/billing/': typeof AuthedBillingIndexRoute
  '/_authed/projects/$projectId/settings': typeof AuthedProjectsProjectIdSettingsRoute
  '/api/environments/$environmentId/download': typeof ApiEnvironmentsEnvironmentIdDownloadRoute
  '/_authed/projects/$projectId/': typeof AuthedProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/pricing'
    | '/sign-in'
    | '/sign-up'
    | '/billing'
    | '/dashboard'
    | '/onboarding'
    | '/api/healthz'
    | '/invite/$invitationId'
    | '/billing/checkout'
    | '/projects/$projectId'
    | '/api/auth/$'
    | '/api/cli/diff'
    | '/api/cli/init'
    | '/api/cli/pull'
    | '/api/cli/push'
    | '/billing/'
    | '/projects/$projectId/settings'
    | '/api/environments/$environmentId/download'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/pricing'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/onboarding'
    | '/api/healthz'
    | '/invite/$invitationId'
    | '/billing/checkout'
    | '/api/auth/$'
    | '/api/cli/diff'
    | '/api/cli/init'
    | '/api/cli/pull'
    | '/api/cli/push'
    | '/billing'
    | '/projects/$projectId/settings'
    | '/api/environments/$environmentId/download'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/about'
    | '/pricing'
    | '/sign-in'
    | '/sign-up'
    | '/_authed/billing'
    | '/_authed/dashboard'
    | '/_authed/onboarding'
    | '/api/healthz'
    | '/invite/$invitationId'
    | '/_authed/billing/checkout'
    | '/_authed/projects/$projectId'
    | '/api/auth/$'
    | '/api/cli/diff'
    | '/api/cli/init'
    | '/api/cli/pull'
    | '/api/cli/push'
    | '/_authed/billing/'
    | '/_authed/projects/$projectId/settings'
    | '/api/environments/$environmentId/download'
    | '/_authed/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AboutRoute: typeof AboutRoute
  PricingRoute: typeof PricingRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiHealthzRoute: typeof ApiHealthzRoute
  InviteInvitationIdRoute: typeof InviteInvitationIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCliDiffRoute: typeof ApiCliDiffRoute
  ApiCliInitRoute: typeof ApiCliInitRoute
  ApiCliPullRoute: typeof ApiCliPullRoute
  ApiCliPushRoute: typeof ApiCliPushRoute
  ApiEnvironmentsEnvironmentIdDownloadRoute: typeof ApiEnvironmentsEnvironmentIdDownloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$invitationId': {
      id: '/invite/$invitationId'
      path: '/invite/$invitationId'
      fullPath: '/invite/$invitationId'
      preLoaderRoute: typeof InviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healthz': {
      id: '/api/healthz'
      path: '/api/healthz'
      fullPath: '/api/healthz'
      preLoaderRoute: typeof ApiHealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/billing': {
      id: '/_authed/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthedBillingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/billing/': {
      id: '/_authed/billing/'
      path: '/'
      fullPath: '/billing/'
      preLoaderRoute: typeof AuthedBillingIndexRouteImport
      parentRoute: typeof AuthedBillingRoute
    }
    '/api/cli/push': {
      id: '/api/cli/push'
      path: '/api/cli/push'
      fullPath: '/api/cli/push'
      preLoaderRoute: typeof ApiCliPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/pull': {
      id: '/api/cli/pull'
      path: '/api/cli/pull'
      fullPath: '/api/cli/pull'
      preLoaderRoute: typeof ApiCliPullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/init': {
      id: '/api/cli/init'
      path: '/api/cli/init'
      fullPath: '/api/cli/init'
      preLoaderRoute: typeof ApiCliInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/diff': {
      id: '/api/cli/diff'
      path: '/api/cli/diff'
      fullPath: '/api/cli/diff'
      preLoaderRoute: typeof ApiCliDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/projects/$projectId': {
      id: '/_authed/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthedProjectsProjectIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/billing/checkout': {
      id: '/_authed/billing/checkout'
      path: '/checkout'
      fullPath: '/billing/checkout'
      preLoaderRoute: typeof AuthedBillingCheckoutRouteImport
      parentRoute: typeof AuthedBillingRoute
    }
    '/_authed/projects/$projectId/': {
      id: '/_authed/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
    '/api/environments/$environmentId/download': {
      id: '/api/environments/$environmentId/download'
      path: '/api/environments/$environmentId/download'
      fullPath: '/api/environments/$environmentId/download'
      preLoaderRoute: typeof ApiEnvironmentsEnvironmentIdDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/projects/$projectId/settings': {
      id: '/_authed/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof AuthedProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
  }
}

interface AuthedBillingRouteChildren {
  AuthedBillingCheckoutRoute: typeof AuthedBillingCheckoutRoute
  AuthedBillingIndexRoute: typeof AuthedBillingIndexRoute
}

const AuthedBillingRouteChildren: AuthedBillingRouteChildren = {
  AuthedBillingCheckoutRoute: AuthedBillingCheckoutRoute,
  AuthedBillingIndexRoute: AuthedBillingIndexRoute,
}

const AuthedBillingRouteWithChildren = AuthedBillingRoute._addFileChildren(
  AuthedBillingRouteChildren,
)

interface AuthedProjectsProjectIdRouteChildren {
  AuthedProjectsProjectIdSettingsRoute: typeof AuthedProjectsProjectIdSettingsRoute
  AuthedProjectsProjectIdIndexRoute: typeof AuthedProjectsProjectIdIndexRoute
}

const AuthedProjectsProjectIdRouteChildren: AuthedProjectsProjectIdRouteChildren =
  {
    AuthedProjectsProjectIdSettingsRoute: AuthedProjectsProjectIdSettingsRoute,
    AuthedProjectsProjectIdIndexRoute: AuthedProjectsProjectIdIndexRoute,
  }

const AuthedProjectsProjectIdRouteWithChildren =
  AuthedProjectsProjectIdRoute._addFileChildren(
    AuthedProjectsProjectIdRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedBillingRoute: typeof AuthedBillingRouteWithChildren
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
  AuthedProjectsProjectIdRoute: typeof AuthedProjectsProjectIdRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedBillingRoute: AuthedBillingRouteWithChildren,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
  AuthedProjectsProjectIdRoute: AuthedProjectsProjectIdRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AboutRoute: AboutRoute,
  PricingRoute: PricingRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiHealthzRoute: ApiHealthzRoute,
  InviteInvitationIdRoute: InviteInvitationIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCliDiffRoute: ApiCliDiffRoute,
  ApiCliInitRoute: ApiCliInitRoute,
  ApiCliPullRoute: ApiCliPullRoute,
  ApiCliPushRoute: ApiCliPushRoute,
  ApiEnvironmentsEnvironmentIdDownloadRoute:
    ApiEnvironmentsEnvironmentIdDownloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
